sessions:
  0:
    name: test
    players:
      - name: AldiiX
        role: Owner
      - name: Mannius
        role: Member
  1:
    name: test2
    players:
      - name: ITM
        role: Owner
      - name: FoFo23
        role: Moderator
messages:
