sessions:
  0:
    name: test
    players:
      - name: AldiiX
        role: Owner
      - name: Mannius
        role: Member
  1:
    name: test2
    players:
      0:
        name: ITM
        role: Owner
      1:
        name: FoFo23
        role: Moderator
messages:
